# This workflow will do a clean installation of node dependencies, build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build - Release - Publish

on:
  push:
    branches: [ "github_actions_development" ]

  pull_request:
    branches: [ "github_actons_development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Perform clean install
      run: npm ci

    - name: Build projects in library
      run: |
        npm run build button --configruation=production
        npm run build hint-expander --configuration=production
        npm run build input --configuration=production
        npm run build page-alert --configruation=production
        npm run build select --configruation=production
        npm run build step-indicator --configuration=production

    - name: Upload dist folder
      uses: actions/upload-artifact@v3.1.3
      with:
        name: distArtifact
        path: dist
        error: Artifact is nonexistant

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download dist folder
      uses: actions/download-artifact@v2.1.1
      with:
        name: distArtifact
        path: dist

    - name: Show dist directory contents
      run: |
        cd dist
        ls

    - name: Make a new release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create 1.0.0-beta.0 --draft
        gh release upload dist

  publish:
    needs: [build, release]
    runs-on: ubuntu-latest

    steps:
      - name: Release to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_FOR_GITHUB_ONTARIO_LRC}}
        run: npm publish dist --tag beta --dry-run
